---
title: "2023_USA_data description"
author: "Group_U"
date: "2025-01-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=TRUE, results='hide'}
packages = (c("ipumsr", "dplyr", "ggplot2", "tidyr", "here", "rmdformats", "srvyr"))

## Now load or install&load all
package.check <- lapply(
  packages,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
      library(x, character.only = TRUE)
    }
  }
)
```

```{r setup, include=True}
#set working documents
setwd("c:/Users/ThomasZhang/Desktop/IC/Health Analytics/cw/data/")

#load package
library(ipumsr)

#read data
ddi <- read_ipums_ddi("usa_00006.xml")
data <- read_ipums_micro(ddi,data_file = "usa_00006.dat")

#check first 4 rows
head(data)
```

```{r, include=TRUE}
#summary data
summary(data)

#n of INCTOT
data %>%
  summarise(count = sum(!is.na(INCTOT))) %>%
  pull(count) %>%
  format(big.mark=",")

#n of UHRSWORK
data %>%
  summarise(count = sum(!is.na(UHRSWORK))) %>%
  pull(count) %>%
  format(big.mark=",")

#check missing data
sum(is.na(data))
```

```{r, include=TRUE}
# check unprocessed data
summary(data$INCTOT)

# calculate quantile
lower_bound <- quantile(data$INCTOT, 0.01, na.rm = TRUE)
upper_bound <- quantile(data$INCTOT, 0.99, na.rm = TRUE)

# filter data
data_cleaned <- data %>%
  filter(INCTOT >= lower_bound & INCTOT < upper_bound)

# check processed data
summary(data_cleaned$INCTOT)

# print boundary, check cut_off 
print(paste("Lower bound (1% quantile):", lower_bound))
print(paste("Upper bound (99% quantile):", upper_bound))

# check how many records are deleted
print(paste("Removed records:", nrow(data) - nrow(data_cleaned)))
print(paste("Percentage removed:", round((nrow(data) - nrow(data_cleaned))/nrow(data)*100, 2), "%"))

```

#数据画图
```{r, include=TRUE}
# ggplot
library(ggplot2)
library(gridExtra)
# 1.Basic descriptive stat

summary_stats <- data %>%
  summarise(
    #dependent variable
    mean_child = mean(NCHILD, na.rm = TRUE),
    sd_child = sd(NCHILD, na.rm = TRUE),
    
    #independent variable
    mean_work = mean(UHRSWORK, na.rm = TRUE),
    sd_work = sd(UHRSWORK, na.rm = TRUE),
    
    #control variables
    mean_age = mean(AGE, na.rm = TRUE),
    sd_age = sd(AGE, na.rm = TRUE),
    mean_educ = mean(EDUC, na.rm = TRUE),
    sd_educ = sd(EDUC, na.rm = TRUE),
    mean_income = mean(INCTOT, na.rm = TRUE),
    sd_income = sd(INCTOT, na.rm = TRUE)
  )

# 2.variables distribution visualisation

#working hours distribution
p1 <- ggplot(data, aes(x = UHRSWORK)) +
  geom_histogram(bins = 30, fill = "gray") +
  labs(title = "working hrs distribution", x = "weekly hours", y = "frequency") + theme_minimal()

#child distribution
p2 <- ggplot(data, aes(x = factor(NCHILD)))+
  geom_bar() +
  labs(title = "child number distribution", x = "n of child", y = "frequency") + theme_minimal()

#metropolitan distribution
metro_type <- data %>%
  group_by(METRO) %>%
  summarise(count = n()) %>%
  mutate(percentage = count/sum(count)*100) %>%
  
  mutate(metro_type = case_when(
    METRO == 0 ~ "Not identifiable",
    METRO == 1 ~ "Central city",
    METRO == 2 ~ "Balance of MSA",
    METRO == 3 ~ "Non-MSA, non farm",
    METRO == 4 ~ "Non-MSA, farm",
    TRUE ~ "Other"
  ))

#education distribution
edu_level <- data %>%
  group_by(EDUC) %>%
  summarise(count = n()) %>%
  mutate(percentage = count/sum(count)*100) %>%
  mutate(education_level = case_when(
    EDUC == 00 ~ "N/A or no schooling",
    EDUC == 01 ~ "Nursery school to grade 4",
    EDUC == 02 ~ "Grade 5, 6, 7, or 8",
    EDUC == 03 ~ "Grade 9",
    EDUC == 04 ~ "Grade 10",
    EDUC == 05 ~ "Grade 11",
    EDUC == 06 ~ "Grade 12",
    EDUC == 07 ~ "1 year of college",
    EDUC == 08 ~ "2 years of college",
    EDUC == 09 ~ "3 years of college",
    EDUC == 10 ~ "4 years of college",
    EDUC == 11 ~ "5+ years of college",
    EDUC == 99 ~ "Missing",
    TRUE ~ "Other"
  ))

# 3. correlation analysis
data %>%
  mutate(age_group = case_when(
    AGE < 30 ~"young",
    AGE < 50 ~ "middle",
    TRUE ~ "old"
  )) %>%
  group_by(age_group) %>%
  summarise(cor = cor (UHRSWORK, NCHILD, use = "complete.obs"))

#print outputs
print("Basic descriptive stat:")
print(summary_stats)
print("\n of metro distribution:")
print(metro_dist)
print(edu_level)
print("\n correlation matrix:")
print(cor_matrix)

#plot
grid.arrange(p1, p2, ncol = 2)

```


```{r, include=TRUE}
#age groups filter
female_data <- data %>%
 
   #filter female data
  filter(SEX == 2) %>%
 
   #select age group 18-49
  filter(AGE >= 18 & AGE <= 49) %>%
  
    # filter 0.01 to 0.99
  filter(
    INCTOT >= quantile(INCTOT, 0.1, na.rm = TRUE) & 
    INCTOT < quantile(INCTOT, 0.99, na.rm = TRUE),
    UHRSWORK >= quantile(UHRSWORK, 0.1, na.rm = TRUE) & 
    UHRSWORK < quantile(UHRSWORK, 0.99, na.rm = TRUE)
  ) %>%
  
  #create group variables
  mutate(
    #by group
    age_group = case_when(
      AGE < 30 ~ "young",
      AGE < 40 ~ "middle",
      TRUE ~ "older"
    ),
    
    #by metro type
    metro_type = case_when(
    METRO == 0 ~ "Not identifiable",
    METRO == 1 ~ "Central city",
    METRO == 2 ~ "Balance of MSA",
    METRO == 3 ~ "Non-MSA, non farm",
    METRO == 4 ~ "Non-MSA, farm",
    TRUE ~ "Other"
    ),
    
    #by education level
    educ_level = case_when(
    EDUC == 00 ~ "N/A or no schooling",
    EDUC == 01 ~ "Nursery school to grade 4",
    EDUC == 02 ~ "Grade 5, 6, 7, or 8",
    EDUC == 03 ~ "Grade 9",
    EDUC == 04 ~ "Grade 10",
    EDUC == 05 ~ "Grade 11",
    EDUC == 06 ~ "Grade 12",
    EDUC == 07 ~ "1 year of college",
    EDUC == 08 ~ "2 years of college",
    EDUC == 09 ~ "3 years of college",
    EDUC == 10 ~ "4 years of college",
    EDUC == 11 ~ "5+ years of college",
    EDUC == 99 ~ "Missing",
    TRUE ~ "Other"
    ))

# 1. basic regression model
model1 <- lm(NCHILD ~ UHRSWORK + AGE + EDUC + INCTOT + factor(METRO) , data = female_data)

# 2. non-linear regression model
model2 <- lm(NCHILD ~ UHRSWORK + AGE + I(AGE^2) + EDUC + INCTOT + factor(METRO), data = female_data)

# 3. Interaction model
model3 <- lm(NCHILD ~ UHRSWORK*AGE + UHRSWORK*factor(METRO) + EDUC + INCTOT, data = female_data)

#group by METRO
models_by_metro <- female_data %>%
  group_by(metro_type) %>%
  group_modify(~{
    model <- lm(NCHILD ~ UHRSWORK + AGE + EDUC + INCTOT, data = .x)
    broom::tidy(model)
  })

#visualisation
ggplot(female_data, aes(x = UHRSWORK, y = NCHILD, color = metro_type)) + 
  geom_smooth(method = "lm") + 
  facet_wrap(~age_group) + 
  theme_minimal() + 
  labs(title = "relationship between WKHRS and nCHILD : by metro and age",
       x = "weekly wkhrs",
       y = "nCHILD",
       color = "metro type")

# 3D analysis
complex_analysis <- female_data %>%
  group_by(age_group, educ_level, metro_type) %>%
  summarise(
    avg_children = mean(NCHILD, na.rm = TRUE),
    avg_workhours = mean(UHRSWORK, na.rm = TRUE),
    n = n()
  )

#compare results
summary(model1)
summary(model2)
summary(model3)

print("按城市类型的回归结果：")
print(models_by_metro)

print("\ndifferent metro types:")
print(complex_analysis)

```

```{r, include=TRUE}
#Model 2 scarlet graph
plot2 <- ggplot(female_data, aes(x = UHRSWORK, y = NCHILD)) + 
  geom_point(alpha = 0.1, color = "gray") + 
  geom_smooth(method = "lm", formula = y ~ x + I(x^2), color = "skyblue") + 
  theme_minimal() + 
  labs(title = "model 2 Non-linear regression",
       x = "weekly work hours",
       y = "number of children")

plot2
```
